python test_contrastive.py -l proj_log_con_vqvae_cl \
                          -x pcn_table_con_vqvae_cl \
                          -m contrast_vqvae \
                          -n pcn \
                          -r data/PCN \
                          -c table \
                          -b 1 \
                          -a proj_log_vqvae_cl/pcn_table_vqvae_cl/vqvae/model/ckpt_epoch120.pth \
                          --ckpt 200 \
                          --grid_size 120 \
                          --gp_batch 1000