python train.py -l proj_log_imle \
                -x pcn_car_imle \
                -m imle_gen \
                -n pcn \
                -r data/PCN \
                -c car \
                -b 10 \
                -a proj_log_ae/pcn_car_ae/ae/model/ckpt_epoch100.pth \
                --lr 5e-4 \
                --save_frequency 10 \
                -e 100 \
		            --vis
